name: Execute plugin
on: 
  workflow_dispatch:


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: nleach999/plugin_test@master
        with:
          sast-log-level: DEBUG
          cxflow-version: 1.6.39
          

    