name: Publish a Release
on: 
  workflow_dispatch:


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: nleach999/plugin_test
        with:
          sast-log-level: DEBUG

    