name: Execute plugin
on: 
  workflow_dispatch:


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Env
        run: |
          pwd
          ls -l
          env

      - name: Test
        uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@usability
        with:
          sast-log-level: DEBUG
          sast-url: ${{ vars.SAST_BASE_URL }}
          sast-team: /CxServer
          sast-username: ${{ secrets.SAST_USERNAME}}
          sast-password: ${{ secrets.SAST_PASSWORD}}
          disable-sca-scan: true
          project-name: sv_test-{branch}
