name: Publish a Release
on: 
  workflow_dispatch:


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: ../action/action.yml
        with:
          action-root: ../action
          sast-log-level: DEBUG
          
    