name: Execute plugin
on: 
  workflow_dispatch:


jobs:
  run-action:
    permissions:
      security-events: write
    runs-on: sca-runner
    steps:
      - name: Env
        run: |
          env
      
      - name: Fetch Code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
  
      - name: Test CxFlow++
        uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@usability
        with:
          sast-log-level: DEBUG
          # disable-sca-scan: true
          sast-url: ${{ secrets.CX_SAST_URL }}
          sast-username: ${{ secrets.CX_SAST_USERNAME }}
          sast-password: ${{ secrets.CX_SAST_PASSWORD }}
          sca-tenant: ${{ secrets.CX_SCA_TENANT }}
          sca-username: ${{ secrets.CX_SCA_USERNAME }}
          sca-password: ${{ secrets.CX_SCA_PASSWORD }}

          



