name: Execute plugin
on: 
  workflow_dispatch:


jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@usability
        with:
          sast-log-level: DEBUG
          cxflow-version: 1.6.39


    