name: Execute plugin
on: 
  workflow_dispatch:


jobs:
  run-action:
    permissions:
      security-events: write
    runs-on: ubuntu-latest
    # runs-on: sca-runner
    steps:
     
      - name: Fetch Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
  
      - name: Test CxFlow++
        uses: checkmarx-ts/checkmarx-cxflow-plusplus-github-action@usability
        with:
          sast-log-level: DEBUG
          # disable-sca-scan: true
          sast-url: ${{ secrets.CX_SAST_URL }}
          sast-username: ${{ secrets.CX_SAST_USERNAME }}
          sast-password: ${{ secrets.CX_SAST_PASSWORD }}
          sca-tenant: ${{ secrets.CX_SCA_TENANT }}
          sca-username: ${{ secrets.CX_SCA_USERNAME }}
          sca-password: ${{ secrets.CX_SCA_PASSWORD }}
          build-container-tag: mcr.microsoft.com/dotnet/sdk:8.0
          # scaresolver-tag: cxnleach/scaresolver-netcore:latest

    
  # probe-windows:
  #   runs-on: windows-latest
  #   steps:
  #     - name: env
  #       run: | 
  #         env
  #         ls -l /
  #         Expand-Archive -?
  #         echo wget: $(which wget)
  #         echo unzip: $(which unzip)
  #         echo curl: $(which curl)
      
  # probe-macos:
  #   runs-on: macos-latest
  #   steps:
  #     - name: env
  #       run: |
  #         env
  #         ls -l /etc/
      

          



